### ISSUE TITLE
我按照那个操作了之后报了这个错不知道是什么问题。。。

### ISSUE THREAD

**Issue by zjy5755202** [shixiaohu2206/hexo-theme-huhu#5]
ERROR Render HTML failed: index.html
TypeError: D:\blog\themes\huhu\layout\layout.ejs:107
    105|     </div>
    106|
 >> 107|     <%- swiftype()%>
    108|   </body>
    109|   <%- gtm_noscript() %>
    110| </html>

Cannot read property 'appKey' of undefined
    at Object.module.exports (D:\blog\themes\huhu\lib\helper\swiftype.js:21:30)
    at eval (eval at compile (D:\blog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:123:17)
    at returnedFn (D:\blog\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiled (D:\blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\blog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\blog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\blog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\blog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\blog\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate (internal/timers.js:439:21)

**Comment by InfiniteXyy** [comment]
在根目录下的`_config.yml`文件里加上这个试试看呢？
```yml
#swiftype
swiftype:
  appKey: ''
```

**Comment by shixiaohu2206** [comment]
> ERROR Render HTML failed: index.html
> TypeError: D:\blog\themes\huhu\layout\layout.ejs:107
> 105|
> 106|
> 
> > > 107|     <%- swiftype()%>
> > > 108|   
> > > 109|   <%- gtm_noscript() %>
> > > 110|
> 
> Cannot read property 'appKey' of undefined
> at Object.module.exports (D:\blog\themes\huhu\lib\helper\swiftype.js:21:30)
> at eval (eval at compile (D:\blog\node_modules\ejs\lib\ejs.js:633:12), :123:17)
> at returnedFn (D:\blog\node_modules\ejs\lib\ejs.js:668:17)
> at Theme._View.View._compiled (D:\blog\node_modules\hexo\lib\theme\view.js:123:48)
> at Theme._View.View.View.render (D:\blog\node_modules\hexo\lib\theme\view.js:29:15)
> at D:\blog\node_modules\hexo\lib\theme\view.js:40:23
> at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
> at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:517:31)
> at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:574:18)
> at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:619:10)
> at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:699:18)
> at _drainQueueStep (D:\blog\node_modules\bluebird\js\release\async.js:138:12)
> at _drainQueue (D:\blog\node_modules\bluebird\js\release\async.js:131:9)
> at Async._drainQueues (D:\blog\node_modules\bluebird\js\release\async.js:147:5)
> at Immediate.Async.drainQueues [as _onImmediate] (D:\blog\node_modules\bluebird\js\release\async.js:17:14)
> at processImmediate (internal/timers.js:439:21)


这个地方没有判空，0.0，等有空我来改一下

**Comment by shixiaohu2206** [comment]
> ERROR Render HTML failed: index.html
> TypeError: D:\blog\themes\huhu\layout\layout.ejs:107
> 105|
> 106|
> 
> > > 107|     <%- swiftype()%>
> > > 108|   
> > > 109|   <%- gtm_noscript() %>
> > > 110|
> 
> Cannot read property 'appKey' of undefined
> at Object.module.exports (D:\blog\themes\huhu\lib\helper\swiftype.js:21:30)
> at eval (eval at compile (D:\blog\node_modules\ejs\lib\ejs.js:633:12), :123:17)
> at returnedFn (D:\blog\node_modules\ejs\lib\ejs.js:668:17)
> at Theme._View.View._compiled (D:\blog\node_modules\hexo\lib\theme\view.js:123:48)
> at Theme._View.View.View.render (D:\blog\node_modules\hexo\lib\theme\view.js:29:15)
> at D:\blog\node_modules\hexo\lib\theme\view.js:40:23
> at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
> at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:517:31)
> at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:574:18)
> at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:619:10)
> at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:699:18)
> at _drainQueueStep (D:\blog\node_modules\bluebird\js\release\async.js:138:12)
> at _drainQueue (D:\blog\node_modules\bluebird\js\release\async.js:131:9)
> at Async._drainQueues (D:\blog\node_modules\bluebird\js\release\async.js:147:5)
> at Immediate.Async.drainQueues [as _onImmediate] (D:\blog\node_modules\bluebird\js\release\async.js:17:14)
> at processImmediate (internal/timers.js:439:21)


嗨，你好，我昨天更新了README.md使用文档，并且在Hexo官方的测试Demo中完整的测试一遍，按照README.md安装，应该就可以正常使用了

如果还不能解决问题，请留言，感谢~

**Comment by zjy5755202** [comment]
好的 感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Utone"<notifications@github.com&gt;; 
发送时间: 2019年11月11日(星期一) 下午4:22
收件人: "shixiaohu2206/hexo-theme-huhu"<hexo-theme-huhu@noreply.github.com&gt;; 
抄送: "朱江源"<1181370590@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shixiaohu2206/hexo-theme-huhu] 我按照那个操作了之后报了这个错不知道是什么问题。。。 (#5)



 
ERROR Render HTML failed: index.html
 TypeError: D:\blog\themes\huhu\layout\layout.ejs:107
 105|
 106|
   
107|     <%- swiftype()%&gt;
 108|
 109|   <%- gtm_noscript() %&gt;
 110|
   
Cannot read property 'appKey' of undefined
 at Object.module.exports (D:\blog\themes\huhu\lib\helper\swiftype.js:21:30)
 at eval (eval at compile (D:\blog\node_modules\ejs\lib\ejs.js:633:12), :123:17)
 at returnedFn (D:\blog\node_modules\ejs\lib\ejs.js:668:17)
 at Theme._View.View._compiled (D:\blog\node_modules\hexo\lib\theme\view.js:123:48)
 at Theme._View.View.View.render (D:\blog\node_modules\hexo\lib\theme\view.js:29:15)
 at D:\blog\node_modules\hexo\lib\theme\view.js:40:23
 at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
 at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:517:31)
 at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:574:18)
 at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:619:10)
 at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:699:18)
 at _drainQueueStep (D:\blog\node_modules\bluebird\js\release\async.js:138:12)
 at _drainQueue (D:\blog\node_modules\bluebird\js\release\async.js:131:9)
 at Async._drainQueues (D:\blog\node_modules\bluebird\js\release\async.js:147:5)
 at Immediate.Async.drainQueues [as _onImmediate] (D:\blog\node_modules\bluebird\js\release\async.js:17:14)
 at processImmediate (internal/timers.js:439:21)
  
嗨，你好，我昨天更新了README.md使用文档，并且在Hexo官方的测试Demo中完整的测试一遍，按照README.md安装，应该就可以正常使用了
 
如果还不能解决问题，请留言，感谢~
